# Generated by Django 6.0.2 on 2026-05-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL (напр. dry-food)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('age', models.CharField(blank=True, choices=[('puppy', 'Щенок'), ('adult', 'Взрослый'), ('senior', 'Пожилой')], max_length=20, verbose_name='Возраст')),
                ('type', models.CharField(blank=True, choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('treat', 'Лакомство')], max_length=20, verbose_name='Тип')),
                ('series', models.CharField(blank=True, max_length=50, verbose_name='Линейка (напр. Sensitive)')),
                ('breed', models.CharField(blank=True, choices=[('all', 'Все породы'), ('small', 'Мелкие'), ('large', 'Крупные')], max_length=50, verbose_name='Порода (напр. large)')),
                ('ingredient', models.CharField(blank=True, choices=[('chicken', 'Курица'), ('lamb', 'Ягненок'), ('salmon', 'Лосось'), ('turkey', 'Индейка'), ('duck', 'Утка')], max_length=50, verbose_name='Ингредиент (напр. lamb)')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Вес (кг)')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
